apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-db-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: auth-db-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.secrets.dbSecretName }}
        property: host

    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.secrets.dbSecretName }}
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.dbSecretName }}
        property: password

    - secretKey: DB_PORT
      remoteRef:
        key: {{ .Values.secrets.dbSecretName }}
        property: port

    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.secrets.dbSecretName }}
        property: dbname