apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-db-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: auth-db-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_URL
      remoteRef:
        key: {{ .Values.secrets.dbSecretName }}
        property: DB_URL

    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.secrets.dbSecretName }}
        property: DB_USERNAME

    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.dbSecretName }}
        property: DB_PASSWORD