apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: retail-platform
spec:
  type: {{ .Values.service.type }}

  selector:
    app: auth-service

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8081