spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/retail_auth_db?options=-c%20TimeZone=Asia/Kolkata}
    username: ${DB_USERNAME:retail_user}
    password: ${DB_PASSWORD:retail_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}