apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: retail-platform-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
  - name: retail-platform
    rules:
    - alert: AuthServiceDown
      expr: kube_deployment_status_replicas_available{
              deployment="auth-service",
              namespace="retail-app"
            } < 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Auth Service Down"
        description: "Auth service has no available replicas."