apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - retail-app
  selector:
    matchLabels:
      app: gateway-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s