name: Reusable Java Build Pipeline

on:
  workflow_call:

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/auth-service

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build + Unit Tests
        run: mvn clean verify

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: services/auth-service/target/site/jacoco

      - name: SonarCloud Scan
        run: >
          mvn sonar:sonar
          -Dsonar.projectKey=akashjaiswal36_retail-platform
          -Dsonar.organization=akashjaiswal36
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: services/auth-service
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: services/auth-service

      - name: Build Docker Image
        run: docker build -t retail/auth-service:${{ github.sha }} .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: retail/auth-service:${{ github.sha }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
