name: Frontend Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'services/frontend/**'
      - 'deploy/helm/frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - '.github/workflows/reusable-java-build.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      ECR_REPOSITORY: frontend
      EKS_CLUSTER_NAME: eks-demo-cluster
      RELEASE_NAME: frontend-service
      NAMESPACE: retail-app

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::562887205095:role/GitHubActionsECRPushRole
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependency
        working-directory: services/frontend
        run: npm ci

      - name: Build frontend
        working-directory: services/frontend
        run: npm run build

      - name: Build Docker image
        working-directory: services/frontend
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Install Helm
        uses: azure/setup-helm@v4


      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ap-south-1 \
            --name eks-demo-cluster

      - name: Who am I?
        run: |
          aws sts get-caller-identity

      - name: Deploy to EKS
        run: |
          helm upgrade --install frontend ./deploy/helm/frontend \
            --namespace retail-app \
            --set image.repository=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }} \
            --set image.tag=${{ github.sha }}